### ISSUE TITLE
Crash on (mod) arrow hitting star fissure

### ISSUE THREAD

**Issue by Gorgok** [XCompWiz/Mystcraft-Issues#117]
Hard to tell what really happened in that lovely mess of a place but from crash log it sounds like a mine and blade arrow shot by a skeleton tried to run for its life through the star fissure...

http://pastebin.com/QhBNQAMy

**Comment by XCompWiz** [comment]
Something about the bug title made me happy. I think because it's nice and mechanical and an interesting little edge case.
I also really like your presentation of it, so it just kept getting better. :P

Looks like the entity might not be possible to save properly, at which point it should just not link, I guess. Might also be a problem with the Star Fissure itself. I'll look into it when I power up my computer in a little while. :)

**Comment by XCompWiz** [comment]
Yup, the entity isn't registered. I've put in a check to catch this, so any entities which cannot be saved will simply be destroyed on link.
