### ISSUE TITLE
Myst-Regenchunk not working?

### ISSUE THREAD

**Issue by LazerusKI** [XCompWiz/Mystcraft-Issues#126]
Just tried this with the Infinity pack.
The world "flickers" shortly and a message tells me that i regenerated some chunks - but nothing changes.

Is there a know conflict with another mod or something like that? or is it simply deactivated?

**Comment by XCompWiz** [comment]
I tested it the other day and it works fine.
What did you expect to change? "regen" basically just resets the chunks.

**Comment by LazerusKI** [comment]
well...i expected that the chunks reset to how they were when the map was created.
https://youtu.be/GC2oew1NqZI
But as you can see...nothing happens.

**Comment by XCompWiz** [comment]
Strange. Must be some conflict with another mod causing the chunks to not unload first.
It's main purpose is dev testing, and I used it when testing things for the latest build.  It's not really meant for "end user" use.
Basically, some other mod prevented the unload so the chunks couldn't be replaced, and since it's not actually a feature I'm not going to try and fix it.  If you want to use it you'll need to track down which mod is causing the conflict.

Good luck. Sorry I can't be of more help here.

**Comment by bit2shift** [comment]
Cause: chunk held by a chunk loader.
Fix: Disable the chunk loader and run the command again.

**Comment by bit2shift** [comment]
Cause: chunk held by a chunk loader.
Fix: disable the chunk loader and run the command again.
