### ISSUE TITLE
Optifine Weather Control Incompatability 

### ISSUE THREAD

**Issue by Dmitchell94** [XCompWiz/Mystcraft-Issues#137]
I am unsure if this is an Optifine bug or a Mystcraft bug but Mystcraft ages seem to ignore Optifines weather off setting.

Optifines weather off system does not disable weather in a world only causes it to not render client side reducing lag caused by weather.

**Comment by XCompWiz** [comment]
Mystcraft renders it's own sky and weather, so that's why.  it doesn't run through the vanilla rendering.
Unfortunately, there's not an easy way to support Optifine in this regard, to my knowledge.  A lot of the time Optifine causes problems with other mods, especially mods that have any kind of rendering, due to the way Optifine does things. Since I don't think Optifine has an API of any kind, I can't interact correctly.
So the issue would probably need to be resolved in Mystcraft, but I don't have a good way of doing that.

**Comment by XCompWiz** [comment]
I'd like a "cantfix" label. :P  I'm willing to fix it, but just can't do so readily.
