### ISSUE TITLE
Unable to optain Chromaticraft Mystcraft pages

### ISSUE THREAD

**Issue by eqdanteon** [XCompWiz/Mystcraft-Issues#144]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/511

The custom pages generated by Chromaticraft cannot but obtained as they are not added to the Mystcraft loot table.  Using Chromaticraft V10b and Mystcraft 0.12.3.01.  Reika has asked for input with resolving the issue so I thought I would post it here as well.  Any assistance would be greatly appreciated.

**Comment by ReikaKalseki** [comment]
Basically, I thought the loot was handled automatically, and have no idea how to add it myself.

**Comment by Zsashas** [comment]
Probably the loot IS handled automatically, but whereas Mystcraft creates most pages for mod blocks itself, Chromaticraft seems to make its own pages, itself.

**Comment by ReikaKalseki** [comment]
It does, and on top of that MystCraft has spontaneously stopped recognizing my pages. I have contacted @XCompWiz, but have yet to get a reply.

**Comment by ReikaKalseki** [comment]
It appears the issue was a timing one. However, these constraints really need to be documented somewhere.

**Comment by XCompWiz** [comment]
You contacted me?  Was it somewhere other than here?

The constraints should be documented in my API, but if I missed some please point them out. :)

Did you find the loot registration stuff in the SymbolValuesAPI?

**Comment by ReikaKalseki** [comment]
> You contacted me? Was it somewhere other than here?

No, it was here, on another thread.

> The constraints should be documented in my API, but if I missed some please point them out. :)

The javadoc for the APIInstanceProvider says to "request an instance via IMC". Intuition and experience with other mods indicates that you would then do your registration to those APIs in postLoad. However, in the case of MystCraft, you actually need to register them at the instant the API is provided. So rather than having receiveAPI cache an API getter and then call that from the mods during postLoad, I had to have the mods register callbacks and then operate on those during receiveAPI.

This is confusing and highly unusual, and it is not helped by the fact that registration at the wrong time simply fails silently inside MystCraft internal code, producing no error or log message.

**Comment by XCompWiz** [comment]
I'll make it fail loudly. That's a very good point.
Ya, the class indicates at the top the timing constraint.
Since I've not used other mods' APIs I couldn't reference common practice, but I wouldn't have a good way to "finalize" a bunch of data other than on postLoad, and that's why the constraint is what it is.

Good you got it working. :D

**Comment by ReikaKalseki** [comment]
> Ya, the API class indicates at the top the timing constraint.

Not for me:
![](http://i.imgur.com/Px3xsVX.png)

**Comment by XCompWiz** [comment]
The SymbolValuesAPI class indicates ITS timing constraints.
Are there other timing constraints not mentioned on the relevant APIs?

**Comment by ReikaKalseki** [comment]
That one at least says it should be before post-init, but I suspect that there will be people who then get confused by the fact you do not receive the calls until IMC (or who just try to send it in main init).
