### ISSUE TITLE
Mystcraft intermod compatibility NEI/Minetweaker

### ISSUE THREAD

**Issue by Nadiir** [XCompWiz/Mystcraft-Issues#166]
Unlinked Book's recipes are incompatible with NEI & Minetweaker.

Everything else craftable (within the mod) is, however, compatible.

**Comment by heldplayer** [comment]
As far as I know, they use a custom recipe class because it needs to copy NBT data from the linking panel to the book.

It won't display in NEI by default but [you can fix it with my NEI addon for Mystcraft](http://minecraft.curseforge.com/projects/nei-mystcraft-plugin).

Not sure how you'd be able to change the recipe with Minetweaker though because of this.

**Comment by XCompWiz** [comment]
Held is correct, the Unlinked Linkbook crafting recipe is actually a recipe class, not a standard grid recipe.  Held is also correct for the why of this: it needs to copy some of the properties from the ingredients to the result.  There isn't a better way to handle this in Minecraft to my knowledge.

I'm open to information on how to do this differently to support this, however.
