### ISSUE TITLE
Fix collation stacking please

### ISSUE THREAD

**Issue by keybounce** [XCompWiz/Mystcraft-Issues#172]
If you are going to do a quick bugfix release, can you please get empty folders from the boosters to stack? Or even be used as binders so we don't have to kill cows?

**Comment by XCompWiz** [comment]
Empty folders should stack and should work as covers. The "empty" state is just a bit weird because of how the NBT data works.  Try dumping the otherwise empty folder into a binder as if you were trying to put in the pages from it; that should force it to be empty.

Fixing the folders so that they end up with no NBT when emptied will take a good bit more work, so may not be something I can put into a quick build.

**Comment by keybounce** [comment]
Empty folders do work in the bookbinder. They do not stack, and do not work in unlinked linking books.
