### ISSUE TITLE
Liquid Black Ink Not Pumpable

### ISSUE THREAD

**Issue by grafvonzan** [XCompWiz/Mystcraft-Issues#174]
It does not appear that liquid black ink is able to be pumped or gathered with a bucket when it has been spawned in as a liquid block. Even gathering the ink with glass vials is not possible. I am also unable to move ink from tanks with a bucket. Is this intentional?

**Comment by heldplayer** [comment]
Yes, the only valid container for liquid black ink is bottles. It's very possible that you can't even pick it up with bottles.

The recipe for ink bottles is a water bottle with an ink sack in a crafting table.

**Comment by grafvonzan** [comment]
Should the page refering to the ink be removes then? I made an age with oceans of ink and was hoping to pump it out for use. As it does not seem the ink can be interacted with at all when it is in the form or a liquid block, is there any point to having a page for it? I guess it works for decoration, but it causes a not insignificant amount of instability, implying that it is valuable.

**Comment by heldplayer** [comment]
There may be plans for it to be usable in some way later. I don't know what the plans are though :P

**Comment by denzuko** [comment]
@grafvonzan Immersive Engineering has a bottling machine that can take fluids (ie ink) in from the back and fill bottles from one side to output into another. It's also been my experience that one can put several stacks of ink bottles into the mystcraft ink mixer. Setting up EnderIO conduits would help in this part.

However one should take into the cannon of Myst, it was a highly spiritual/philosophical process for D'ni and a highly specialized one for the Gartnerney to write linking and descriptive books therefore while Uru may have us believe there was tons of books. Riven and Exile show us that it was a selective process to learn and automation would have not been available for the creation of books. 

With that said it's my understanding that XCompWiz is attempting to be closer to Cyan's original view of link books instead of say Ubisoft's view. But do try my suggestion above:

IE bottling Machine ( tank of ink, bottles from storage system ) > storage system (ink bottles ) > EnderIO conduit > Mystcraft Ink Mixer

**Comment by XCompWiz** [comment]
Ya, I need to rework ink.  You are correct that I'm more targeting Cyan's design than anything that came later.  RAWA is a good resource.
I have broken a few of the rules, and intend to allow a few more gamey mechanics. (ex. following books are something I want to allow, but they should be expensive.)  This is more to do with meshing with Minecraft and making the mod fun to play.

Nice bottling solution!

**Comment by grafvonzan** [comment]
@denzuko Awesome, thanks for the solution! I didn't know of any blocks that are able to interact with ink.

**Comment by denzuko** [comment]
@XCompWiz I'd love to see book entities that follow a player. That would change up the game a lot! Maybe one could even have books that can be hostile to players?

**Comment by XCompWiz** [comment]
I think that black ink blocks can be pumped, just not picked up with buckets.  The desk even supports ink being pumped in.  Otherwise there just isn't bucket support for Mystcraft black ink (kinda on my list, still).
