### ISSUE TITLE
Missing graphic in opened descriptive book

### ISSUE THREAD

**Issue by koril-k** [XCompWiz/Mystcraft-Issues#185]
In Mystcraft for 1.11.2 the graphics for the right side of an opened descriptive book is missing. Instead it shows four squares: two of them black, the other two pink. I try to upload a screenshot.
![screen](https://user-images.githubusercontent.com/30242675/28283707-d9c3b8fe-6b2e-11e7-9605-c3b325cd8979.png)

**Comment by heldplayer** [comment]
I think the cause of this issue is that the referenced texture is named "bookui_pageR.png", however with recent MC versions a requirement was added for all resource names and domains to be lowercase. This explains why the front and back both don't load, and is also the cause for pages in a GUI to not properly render if they're not in item form.

**Comment by Ajama11** [comment]
I opened up the .jar and renamed bookui_pageR.png and bookui_pageL.png to bookui_pager.png and bookui_pagel.png respectively, and they showed up properly.

**Comment by heldplayer** [comment]
Didn't think that would work, good to know that works!

**Comment by cragrim** [comment]
Got the same issue!
http://imgur.com/a/47D2n

**Comment by XCompWiz** [comment]
Interesting!
This doesn't happen from dev, so it only shows up in the jar format.  Should be an easy fix. Thanks for reporting it! :)

**Comment by XCompWiz** [comment]
I think this was caused by some stale cache data.  I deleted the offending files from the cache so the next build should have the right ones. :P
