### ISSUE TITLE
Ink Mixer ink effect flashing when adding items/grabbing a page (sync issue?)

### ISSUE THREAD

**Issue by heldplayer** [XCompWiz/Mystcraft-Issues#196]
As the title says, when adding items to the ink in the Ink Mixer GUI, the color starts flashing. Adding more items increases the effect. Likewise, making a page from the current ink causes the ink to start flashing as well. Closing and re-opening the GUI gets rid of the flashing. You can see the effect happening [here](https://ss.heldplayer.blue/XE3mncge). 

I have a sneaking suspicion this is a networking sync issue, wherein the server keeps sending updates on what the displayed gradient should be, resulting in all previous states since opening the GUI to be fighting over which one is correct.

EDIT: Did a little test and this does not appear to happen in 1.7.10 (would be really awkward if it did 😛), so must be something recent.

**Comment by XCompWiz** [comment]
Some of the network stuff did change with the update, so it might have resulted in some race condition stuff / etc.
I have a guess as to the cause. Specifically, I think that it might be the same issue updating the writing desk had in the new version, where the network sends an nbt from the server and the client modifies it resulting in the server copy being modified in single-player (because they got rid of the serialization / deserialization pass when in single-player).
We caught and fixed that issue before the first updated release, but other similar issues may have leaked through.

**Comment by XCompWiz** [comment]
Looks like my guess was wrong.  The stuff sent is packed an unpacked whenever sent.
However, it looks like the packet was being spammed once built, so once a state change occurred it would be resent until the GUI closed. Thus every state was constantly resent from the server. (Packets to send list wasn't being cleared out.)
So seems your guess was exactly on the nose. :D  I apparently didn't read it carefully enough the first time.

Seems to fix the issue. Should be good in next build.
Thanks for reporting it, Held! :D
