### ISSUE TITLE
[1.11.2 - 0.13.2.00] Black Ink and Crystal pages missing?

### ISSUE THREAD

**Issue by michaeljcoffey** [XCompWiz/Mystcraft-Issues#209]
In the "All" view of the symbol portfolio, neither "Black Ink" nor "Crystal" appear as options to find.  And, perhaps needless to say, I haven't found any either.  FWIW, I've searched for both English and Latin terms with the game language set to both English and Latin.

Crystalline Formations still exists as a page, but it seems you can't write a crystalline formation made of crystal.  :)

**Comment by heldplayer** [comment]
I think Black Ink not being in there is intentional/due to the fact that they don't want you to place down ink in the world.

Crystal sounds like an odd one to be missing. Can't check right now but it might have gotten left out somewhere, xComp or HellFire will probably know what's going on with it though.

**Comment by XCompWiz** [comment]
Crystal is not missing in my dev environment. Can you provide screenshots of what you are doing to try to see it?
Black Ink is probably intentionally omitted, but I might change that later. :)

**Comment by XCompWiz** [comment]
Black ink wasn't missing, just missing its localization. That'll be fixed next release.
Are you still having trouble getting the crystal block page?

**Comment by XCompWiz** [comment]
OK :) The localization issue is fixed in the next release, and there's a task for that, I think, so I'll go ahead and close this one. :) Cheers!
