### ISSUE TITLE
Snow-blocks causing stack overflows.

### ISSUE THREAD

**Issue by foone** [XCompWiz/Mystcraft-Issues#33]
I've generated two worlds today which triggered this error (shutting down the server!) when entered:

https://paste.ee/p/QAgdW

It appears to be a crash in vanilla minecraft code, but it's being triggered by Mystcraft world-gen. The only other reference to this sort of crash I've seen involved admins replacing all the air blocks with snow blocks, which didn't happen here. I created the world and then had it crash on me immediately. 

Here's the agedata for this instant-crash world: http://foone.org/minecraft/nbt/agedata_31.dat

Mystcraft 0.11.0.00 on Minecraft Forge 10.13.2.1236 and Minecraft 1.7.10

**Comment by XCompWiz** [comment]
I think I might have used the wrong snow for something... again...
The naming keeps changing.  It's rarely intuitive and it's sometimes even backwards.

**Comment by Jaytractive** [comment]
I generated an age that was an flat land ocean with Ars Magica 2 liquid. The age spawned with snow on it. When I broke a piece of snow the server instantly crashed. Then when it starts back up it shows that world having less snow. This crash only happens only when there is snow on top of the liquid and it is updated.

**Comment by XCompWiz** [comment]
Ah!  That’s a really useful piece of information! Thank you!

It likely has something to do with cascading updates, so there might be an underlying issue somewhere, but at any rate the root cause is that snow is being generated inverse the way it should be (snow is being placed where it isn’t meant to be possible; ex. on water/aura nodes; and isn’t being placed normally on terrain).  This is already fixed in the dev builds.

**Comment by XCompWiz** [comment]
I think this should be handled now.  Please let me know if not.
