### ISSUE TITLE
Low tps

### ISSUE THREAD

**Issue by Pilad** [XCompWiz/Mystcraft-Issues#41]
After add this mod(mystcraft-1.7.10-0.11.1.00.jar ) tps is very slow. 0.5-1.5 
On version mystcraft-1.7.10-0.11.0.00.jar - 18-20 tps

**Comment by RuhaiHu** [comment]
I would like to add I am seeing a DIM folder DIM_MYST-2147483648 in opis its called CONTROL with thousands of loaded chunks entities etc as the server continues to run on the newly release version. I have tried to delete folder from server but it gets recreated on reload and doesn't seem to cause the issue mentioned above. 

Again first world load tps extremely low like Pilad mentions. Then I stopped my server, and then deleted the folder I mentioned above. Starting the server caused it to be recreated but not cause the issues mentioned above.

I have tried forcing my self to tpx into it only to crash the client only I believe.

**Comment by heldplayer** [comment]
It's a profiling age, it gets created the first time you open a world to calculate how much of what ores exist in the overworld. Yes it'll be a bit slower at the start but it should finish and unload in the first 5 minutes (unless your PC/server is really slow).

As for TPXing into the age, I reported that before and xComp said he fixed it, though something might've slipped.

**Comment by XCompWiz** [comment]
If you have crash logs from TPXing into the dimension I'd like them.
Otherwise, this dimension is the instability fix.  It's how Mystcraft knows what a normal world is like in terms of composition.  It must generate some chunks in this dimension, but it doesn't save them.

I can reduce the chunks generated per tick for the profiling, but that will increase the duration and thus the delay before Mystcraft worlds can have working instability.
1.8 will improve this, as the generation for the dim will be threaded.

**Comment by Cobra1117** [comment]
@XCompWiz If it's possible to display a warning in the console, I think that would do wonders. I spent a couple of hours adding/removing mods trying to figure this one out before tracing it back to Mystcraft. A simple "Your game's going to lag for a few minutes, be patient" could save people a lot of trouble.

**Comment by RuhaiHu** [comment]
I did not wait a few minutes because opis was reporting 10K+ worth of chunks loaded on one of my world loads where I did let it run for a bit.

Since I didn't let it run. Should I? Or if possible like mentioned above put a warning in the console and maybe prevent world access until its done if possible. I will see if I can find/have still the log for the client crash.

**Comment by XCompWiz** [comment]
A pop-up screen might be possible, yes. :)
I could also add an optional (config setting) to kick players off a server until it's done with the initial profiling.

**Comment by XCompWiz** [comment]
As to tps, see #43.  Those fixes should improve performance a good bit.
I'll try to add the pop-up screen now.

**Comment by XCompWiz** [comment]
An Achievement-style popup has been added to inform the client that profiling is ongoing on login. Another popup informs of profiling completion.
I'll add the server kick option still, and I have an optimization based on empty chunks planned.  Those should solve most issues, hopefully.

**Comment by mSt3in** [comment]
Thanks @XCompWiz for closing #50.  I got an idea now of what you use dummy for now.

If I may, the client popup is not as useful to servers...some basic output in the server log would be nice: one Start, and one complete message is sufficient.

..,personally, I'd go as far as stopping any client to connect until you are finished with what you need to do.

**Comment by XCompWiz** [comment]
I added a server log message for starting and ending profiling last night, so hopefully that'll do.

A progress bar thing is possible, as I know how much total work needs to be accomplished.  An ETA might be tricky, though.
I'm not sure where/how I'd display this progress bar for now, though, so I'm not going to worry about it atm.

A config flag to kick clients until baseline profiling is planned, and I'll probably do that right now.  I've actually already written the code as another utility mod and just need to integrate it.

**Comment by XCompWiz** [comment]
And that should cover that config flag. :)
"B:options.profiling.baseline.disconnectclients"
default is false.

**Comment by XCompWiz** [comment]
I think that covered everything for this issue. I'm going to close it for now. If there are any issues in the next build, please do report them by creating a new issue. :)

**Comment by mSt3in** [comment]
Fantastic!  thank you!

**Comment by mSt3in** [comment]
Man, that profiling is crazy hard to deal with on SP.

SMP; we know why and that's fine.  It takes 10-15 on myst alone.  Throw in some modpack buffet and the time goes up to 20+ and may even require a restart or two but whatever.

SP on the other hand, players just stop and play something else.

Is there anything you might be able to do to yield and run that code more passively?  A new world...won't be able to jump into mystcraft right away, normally.  There should be plenty time to profile in the background before they can get what they need to start entering different ages, IDK if that's possible.  I would expect requiring profiling to be complete before creating an age.

**Comment by mSt3in** [comment]
I have noticed that profiling plays nice with unexpected restarts....good job on that!

**Comment by XCompWiz** [comment]
It's only one chunk a tick, and I have to do it on the tick interval (because you can't generate more than one dimension at a time in 1.7.10).  In 1.8 it'll be better simply because I'll be able to thread it.

On the other hand, I've tested this on the FC2 instance with my latest Mystcraft build, and couldn't even tell Mystcraft was doing anything.  I'm not sure what else I can do at this point.

And thanks. :) I generally try to make my code as robust as possible. :)  I can still make errors, of course, as evidenced by recent builds, but I do shoot for robust.
