### ISSUE TITLE
0.11.1 no longer compatible with cauldron

### ISSUE THREAD

**Issue by Kiwec** [XCompWiz/Mystcraft-Issues#44]
Server can't start (any cauldron version, up to cauldron-1.7.10-1.1307.06.218). Vanilla forge works fine.

Crash log :
http://pastebin.com/Bna4L8Vz

**Comment by XCompWiz** [comment]
As previously stated, I don't actively support Cauldron, as it's not my target platform.

The missing field seems to be on their side.  The field is readily available on Forge, so Cauldron has removed it.  I can't do anything about this, as, at least on Forge, it's necessary for me to use so that chunks load/unload properly.
