### ISSUE TITLE
Crash on world-gen (overworld, new server)

### ISSUE THREAD

**Issue by mSt3in** [XCompWiz/Mystcraft-Issues#54]
https://github.com/XCompWiz/Mystcraft-Issues/issues/53

Hello, this is seems to be a common problem with the profiler. It's blowing the heap no matter how much ram you give it.  Workaround is to just keep restarting the server; it continues and finishes.

**Comment by XCompWiz** [comment]
Strange...  I can check for a memory leak, but it doesn't seem like it's a pure Mystcraft problem.  Can you verify if it happens to you without other mods?

**Comment by mSt3in** [comment]
I cannot.  I'm 100% sure it won't happen without other mods.

I've pulled a few to no avail.  Not sure who to finger.

IDK, whatever it's worth , here is the list.


AnimationAPI-1.7.10-1.2.4.jar
AOBD-2.5.0.jar
AppleCore-mc1.7.10-1.1.0.jar
appliedenergistics2-rv2-beta-18.jar
Aroma1997Core-1.7.10-1.0.2.13.jar
AromaBackup-1.7.10-0.0.0.5.jar
AsieLib-1.7.10-0.3.10.jar
backpack-2.0.1-1.7.x.jar
BiblioCraft[v1.10.2][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[Natura][v1.5].jar
BigReactors-0.4.2A2.jar
BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar
BloodMagic-1.7.10-1.3.1-7.jar
buildcraft-6.4.4.jar
Carpenters Blocks v3.3.5 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel2-2.3.7.34.jar
CodeChickenCore-1.7.10-1.0.4.35-universal.jar
CoFHCore-[1.7.10]3.0.0RC7-211.jar
CoFHLib-[1.7.10]1.0.0RC7-127.jar
commons-codec-1.9.jar
commons-compress-1.8.1.jar
CompactSolars-1.7.10-4.4.39.315-universal.jar
DescriptionTags-1.0-1.7.10.jar
EnderIO-1.7.10-2.2.8.349.jar
EnderStorage-1.7.10-1.4.5.29-universal.jar
EnderZoo-1.7.10-1.0.9.18.jar
EnhancedPortals_1.7.10-universal-3.0.10.jar
extrautilities-1.2.2.jar
fognerf-1.7.10-0.4.jar
Galacticraft-Planets-1.7-3.0.11.306.jar
GalacticraftCore-1.7-3.0.11.306.jar
GardenStuff-1.7.10-1.5.3.jar
GraviSuite-1.7.10-2.0.3.jar
growthcraft-apples-1.7.10-2.1.0.jar
growthcraft-bamboo-1.7.10-2.1.0.jar
growthcraft-cellar-1.7.10-2.1.0a.jar
growthcraft-core-1.7.10-2.1.0a.jar
growthcraft-grapes-1.7.10-2.1.0.jar
growthcraft-hops-1.7.10-2.1.0.jar
growthcraft-rice-1.7.10-2.1.0a.jar
Hats-4.0.1.jar
HatStand-4.0.0.jar
IC2NuclearControl-2.1.2a.jar
iChunUtil-4.2.0.jar
industrialcraft-2-2.2.695-experimental.jar
INpureCore-[1.7.10]1.0.0B9-54.jar
InventoryTweaks-1.59-dev-152.jar
ironchest-1.7.10-6.0.62.742-universal.jar
Jabba-1.2.1a_1.7.10.jar
malisiscore-1.7.10-0.11.1.jar
malisisdoors-1.7.10-1.4.4.jar
Mantle-1.7.10-0.3.2.jar
Mekanism-1.7.10-8.0.3.203.jar
MekanismGenerators-1.7.10-8.0.3.203.jar
MekanismTools-1.7.10-8.0.3.203.jar
MicdoodleCore-1.7-3.0.11.306.jar
MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar
MineMenu-1.7.10-1.2.0.B44-universal.jar
MineTweaker3-1.7.10-3.0.9C.jar
MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar
MobiusCore-1.2.4_1.7.10.jar
ModTweaker2-0.7.5.jar
Morpheus-1.7.10-1.5.26.jar
MrCrayfishFurnitureModv3.4.7(1.7.10).jar
mystcraft-1.7.10-0.11.2.00.jar
natura-1.7.10-2.2.0.1.jar
neiaddons-mc1710-1.12.4.16.jar
NEIIntegration-MC1.7.10-1.0.7.jar
NotEnoughItems-1.7.10-1.0.4.90-universal.jar
ObsidiPlates-1.7.10-universal-3.0.0.18.jar
OpenBlocks-1.7.10-1.3-snapshot-571.jar
OpenComputers-MC1.7.10-1.5.4.11-universal.jar
OpenModsLib-1.7.10-0.6-snapshot-323.jar
Pam's HarvestCraft 1.7.10g.jar
ProjectRed-1.7.10-4.5.15.75-Base.jar
ProjectRed-1.7.10-4.5.15.75-Compat.jar
ProjectRed-1.7.10-4.5.15.75-Integration.jar
ProjectRed-1.7.10-4.5.15.75-Lighting.jar
ProjectRed-1.7.10-4.5.15.75-Mechanical_beta.jar
ProjectRed-1.7.10-4.5.15.75-World.jar
Railcraft_1.7.10-9.5.0.0.jar
RandomThings-2.2.4.jar
RedstoneArsenal-[1.7.10]1.1.0RC7-65.jar
Ruins-1.7.10.jar
SpiceOfLife-mc1.7.10-1.2.3.jar
statues-1.7.10-2.1.4.jar
TConstruct-1.7.10-1.8.3b.jar
Thaumcraft-1.7.10-4.2.3.5.jar
thaumcraftneiplugin-1.7.10-1.7.jar
thaumicenergistics-0.8.9.0b-rv2.jar
ThaumicExploration-1.7.10-1.1-37.jar
ThaumicTinkerer-2.5-1.7.10-162.jar
ThermalDynamics-[1.7.10]1.0.0RC7-98.jar
ThermalExpansion-[1.7.10]4.0.0RC7-141.jar
ThermalFoundation-[1.7.10]1.0.0RC7-62.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.2.jar
warpbook-1.7.10_2.0.36.jar
[1.7.10]StartingInventory-universal-1.7.10.r03.jar

Baubles-1.7.10-1.0.1.10.jar
CodeChickenLib-1.7.10-1.1.3.127-universal.jar
commons-codec-1.9.jar
commons-compress-1.8.1.jar
ForgeMultipart-1.7.10-1.1.1.325-universal.jar
MrTJPCore-1.7.10-1.0.5.11-universal.jar
[1.7.10]bspkrsCore-universal-6.16.jar

**Comment by heldplayer** [comment]
Best you can do is by using trial and error to find the offending mod.

1. Remove all mods that don't or shouldn't add worldgen

2a. If it still happens, continue to 4

2b. If the problem is fixed, re-add the mods you removed and remove the ones that you didn't.

3a. If it still happens, continue to 4

3b. If the problem is fixed, ~~pull out your hairs~~ re-add all the mods again and continue to step 4

4. Repeat from step 1 until the mod(s) are found but instead of removing mods that add worldgen, remove about half of the mods to narrow down the cause.

Note that this process can take some time and isn't perfect, different mod interactions can cause these kinds of issues and you might hit a point where you're unsure what the cause actually is.

**Comment by XCompWiz** [comment]
This method is basically binary search.  Simplified:
Remove half.  If the error stops, the cause exists within the half you removed, if it persists, it's i nthe half you didn't.
Keep whichever half contains the error, and repeat the removal step until you are left with only one mod.
This method works well in computer searches as well as card tricks.

The flaw here is that we assume that there's a single mod (apart from Mystcraft) which is interacting with things, rather than, say, five.  In practice, it tends to be one mod, though.

**Comment by mSt3in** [comment]
Say that's a great idea; I'll do the divide and conquer thing.  Hopefully I'll also discover which one(s) make profiling so gruesomely slow for me.

I'll report back.

**Comment by mSt3in** [comment]
I hereby finger biomes'o'plenty.  100% sure.  It took 7 cycles to binary search it, as you suggested.  

I Pull BoP from the pack and profiling completes in almost the same amount of time as it does I have only mystcraft loaded. (On this comp, that would be 5 min.)

I put BoP and mystcraft in by themselves, and it takes a looong time.  Put in everything with BoP, it takes a really really long time and may even crash.

Now that I know what does it....I got to admit, I'm not readily willing to leave BoP out.   Any thoughts?

**Comment by XCompWiz** [comment]
Clearly, the best course of action is to report it to them. :P  Hopefully it will get fixed.  You can link to this issue if you like. I'd like a link to that report here, if you will. :)

**Comment by plaguewolf** [comment]
i am having what i assume is a related issue, potentially the same.

using mystcraft 0.11.4.00

using both forge 1291 & 1307 on the server side, during what i assume to be the "profiling" right before the overworld spawn generation i get a bajillion WARN messegaes spammed to console, before it crashes, atm i am trying the 'keep restarting the server until it finishes profiling' trick metioned above.

as an idea of what is happening, the console spame left me with a 2.4GB log file XD
i cant even open it to copy paste the relevant informations...

mystcraft was complaining about emtychunks with worlprovider dummy or something like that.

likewise i also have BOP, and about 199 other mods...

**Comment by XCompWiz** [comment]
Sounds like something unrelated, actually.  I'd recommend making a new issue and attempting the binary search method described above to track down the interacting mods.

**Comment by Nomago** [comment]
I'm getting the same issue with crashes during the Profiling, but I don't have BoP in my ModPack. Here's the mods I do have:


AppleCore-mc1.7.10-1.1.0.jar
appliedenergistics2-rv2-beta-26.jar
Baubles-1.7.10-1.0.1.10.jar
BetterAnvil-4.0.0.0-alpha-1.jar
BiblioCraft[v1.10.2][MC1.7.10].jar
BigReactors-0.4.3A.jar
buildcraft-6.4.8.jar
Carpenter's Blocks v3.3.5 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.16-universal.jar
Chisel2-2.3.10.37.jar
ChiselFacades-1.7.10-2.10-cricket.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CoFHCore-[1.7.10]3.0.2-262.jar
Decocraft-v1.12b_1.7.10.jar
EnderIO-1.7.10-2.2.8.367.jar
EnderStorage-1.7.10-1.4.5.27-universal.jar
ExtraCells-1.7.10-2.2.65b102.jar
ExtraTiC-1.7.10-1.0.3.jar
extrautilities-1.2.4.jar
fastcraft-1.21.jar
FastLeafDecay-1.7.10-1.0.jar
funky-locomotion-1.7.10-beta-5a.jar
growthcraft-apples-1.7.10-2.1.0.jar
growthcraft-cellar-1.7.10-2.1.0a.jar
growthcraft-core-1.7.10-2.1.0a.jar
growthcraft-grapes-1.7.10-2.1.0.jar
growthcraft-hops-1.7.10-2.1.0.jar
growthcraft-rice-1.7.10-2.1.0a.jar
industrialcraft-2-2.2.710-experimental.jar
InGameInfoXML-1.7.10-2.8.1.80-universal.jar
InventoryTweaks-1.58-147.jar
ironchest-1.7.10-6.0.62.742-universal.jar
Jabba-1.2.1a_1.7.10.jar
LunatriusCore-1.7.10-1.1.2.21-universal.jar
Mantle-1.7.10-0.3.2.jar
Mekanism-1.7.10-8.1.1.225.jar
MekanismGenerators-1.7.10-8.1.1.225.jar
MekanismTools-1.7.10-8.1.1.225.jar
MineFactoryReloaded-[1.7.10]2.8.0-104.jar
MineTweaker3-1.7.10-3.0.9C.jar
MobiusCore-1.2.5_1.7.10.jar
ModTweaker 2-0.7.5.jar
mystcraft-1.7.10-0.11.4.00.jar
neiaddons-mc1710-1.12.5.17.jar
NEIIntegration-MC1.7.10-1.0.7.jar
NetherOres-[1.7.10]2.3.0-12.jar
NotEnoughItems-1.7.10-1.0.4.95-universal.jar
OpenBlocks-1.7.10-1.4.jar
OpenModsLib-1.7.10-0.7.jar
Opis-1.2.5_1.7.10.jar
Pam's HarvestCraft 1.7.10g.jar
Ruins-1.7.10.jar
SimplyJetpacks-MC1.7.10-1.4.1.jar
Stackie-1.7.10-1.5.1.31-universal.jar
TConstruct-1.7.10-1.8.3b.jar
ThermalDynamics-[1.7.10]1.0.0-122.jar
ThermalExpansion-[1.7.10]4.0.1-182.jar
ThermalFoundation-[1.7.10]1.0.0-81.jar
TiCTooltips-mc1.7.10-1.2.3.jar
twilightforest-1.7.10-2.3.5.jar
UpdateCheckerMod-1.7.10.jar
VeinMiner-1.7.10_0.26.1.unknown.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.2.jar
Wawla-1.2.1_1.7.10.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar



CodeChickenLib-1.7.10-1.1.3.127-universal.jar
ForgeMultipart-1.7.10-1.1.2.331-universal.jar


EJML-core-0.26.jar



Everything seems fine for a few minutes, but then I get a huge slowdown in my world and then a crash. This happens when first starting a whole new world during the profiling phase. If I can exit the world before the crash and restart Minecraft, I can then reopen the world and the profiling finishes and everything is fine.

**Comment by mSt3in** [comment]
>FastLeafDecay-1.7.10-1.0.jar

Recommend you use RandomThings instead.  (You also get bloodmoons, but those can be disabled if you want.)

> twilightforest-1.7.10-2.3.5.jar

This is probably your problem, right there.

> Ruins-1.7.10.jar

This is also problematic sometimes.  Atomic Striker's method of inserting schematics into a world is really slow and glitch-y.  Ruin's isn't too bad...his Towers mod OTOH...it's bad, real bad.

**Comment by mSt3in** [comment]
> This happens when first starting a whole new world during the profiling phase. If I can exit the world before the crash and restart Minecraft, I can then reopen the world and the profiling finishes and everything is fine.

Yes, in 1.7.10 the world is basically unplayable during the profiling phase.

**Comment by Nomago** [comment]
>Recommend you use RandomThings instead. (You also get bloodmoons, but those can be disabled if you want.)

I tried RandomThings and didn't want anything it added except the leaf decay, so why would I want it over FastLeafDecay?

>This is probably your problem, right there.

The same thing happens when I take out TwilightForest, also I have disabled the TwilightForest biomes in Mystcraft as per suggestion.

> This is also problematic sometimes. Atomic Striker's method of inserting schematics into a world is really slow and glitch-y. Ruin's isn't too bad...his Towers mod OTOH...it's bad, real bad.

Again when I've taken this mod out it still does the same thing.

Though its not as bad after updating to 11.4, it still happens. I've been trying the binary search to determine which mod it might be for my pack, but have had no luck. It leads me to believe its a combo of more than one mod.

Another thing of note is that once profiling completes I get this in the log.
>[10:36:14] [Server thread/INFO] [Mystcraft/]: Baseline Profiling for Instability completed.
>[10:36:14] [Server thread/WARN] [FML/]: Unexpected world unload - world -2147483648 is already unloaded
>[10:36:32] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Test Three
>[10:37:02] [Server thread/DEBUG] [FML/]: The world 1991df58 (Test Three) may have leaked: seen 30 times.

>[10:37:17] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Test Three
>[10:37:52] [Server thread/DEBUG] [FML/]: The world 1991df58 (Test Three) may have leaked: seen 35 times.

When Profiling works, the dimension unload isn't already unloaded, but when it crashes, somehow the dimension has already been unloaded.

**Comment by XCompWiz** [comment]
The crash log would be handy, Nomago, and I'd prefer you make a new issue.  We can related issues later, but if this is a different thing I don't want two issues in one ticket.

**Comment by Nomago** [comment]
no problem. I will start a new issue with the log.

**Comment by XCompWiz** [comment]
Should be much better in current version.
