### ISSUE TITLE
Extreme lag with latest versions of Mystcraft

### ISSUE THREAD

**Issue by ajthemacboy** [XCompWiz/Mystcraft-Issues#61]
Hi, I don't know how else to put this.. but lately, Mystcraft really lags a lot for my server.

This didn't happen on previous versions of Mystcraft. Other dimensions generate perfectly fine; Twilight Forest, the Nether, and RFTools dimensions. However when a player creates a Mystcraft dimension, TPS drops to 1-2, and there are lots of freezes and player timeouts.

I am running FTB Infinity 1.3.4 and Mystcraft 0.11.0.00. This did not happen in previous 1.7 modpacks. 

I'm also running Cauldron. Lately I've been using the WorldBorder plugin to pregenerate Mystcraft worlds and also to set borders. I can provide Cauldron timings data if necessary. 

I am not using FastCraft, which comes with Infinity, as it is incompatible with Cauldron.

**Comment by XCompWiz** [comment]
I would like to help, but this isn't enough to even point out the problem.  It's not even enough to say there's a problem in Mystcraft.
You may wish to try updating to at least 0.11.2, as there were some performance improvements of late.

Unless you can provide some kind of actual profiling data, I can't help here.  Any mod's generation could be the culprit.

**Comment by ajthemacboy** [comment]
How can I profile? With spigot timings?

**Comment by XCompWiz** [comment]
I'm afraid you'll have to figure that one out yourself. There are tools, but I'm uncertain if the ones I use were available in general.

**Comment by ajthemacboy** [comment]
I don't know if I can run the Java JDK profiler on Ubuntu server, but I can
try that if you think it will be better.

**Comment by XCompWiz** [comment]
Try whatever you can try, and well see. :)

**Comment by ajthemacboy** [comment]
Here's spigot timings:  http://timings.aikar.co/?url=10754979

Having issues with JVisualVM. The timings aren't the longest but my players were getting mad..

**Comment by XCompWiz** [comment]
I'm not sure these timings tell us anything.  Just that some dims are taking more time, but not why.

Can you try this with only Mystcraft and see how that fares?

You might also try binary searching to see if a singular mod is producing this effect (remove half the other mods, see if the problem persists, use the half with the problem).

**Comment by ajthemacboy** [comment]
Binary testing is really not viable. In a modpack with 200+ mods,
restarting and stopping the game with 5 minute load times, plus world gen
and inventory scrambling, would take a while, even with 50 mods. I'm about
to try with only Mystcraft, though.

**Comment by ajthemacboy** [comment]
In a singleplayer world with only Mystcraft 0.11.0.00 installed, there was little lag, other than the usual chunkloading lag. 

When trying to update my Infinity server to 0.11.3.00, it crashed. Crash report: http://pastebin.com/enqs3fP9

Still, RFTools dimensions do not lag, which leads me to believe this is an issue localized to Mystcraft.

**Comment by seantherobonaut** [comment]
Indeed it does. Which is really strange. As you mentioned it isn't as bad in SSP. Which leads me to believe it is something with cauldron. Which we both know it is near impossible to run a good server without. Instead of removing mystcraft entirely (because I love the mod) I will just disable the creation or use of Descriptive Books. I will add a custom recipe for crystals because I still want players to be able to use portals. It seems like a viable solution for now.

Is there any way to get a descriptive book other than making it through a book binder? Can you find a descriptive book in dungeon chests?

Also with a custom recipe. I think an x of nether quarts and the rest with lapis is a good recipe for crystals for now? Or is that too easy? I mean finding crystals isn't that hard in mystcraft dimensions so no need to make crystals hard to craft right?

It seems I need to add the recipe back for link modifiers too lol. Not sure why they were removed but I can add a custom recipe for them. I love minetweaker. Works for everything.

**Comment by ajthemacboy** [comment]
On my old server I just disabled Book Binders and Notebooks in the config, effectively banning Mystcraft creation. Then I pregenerated a single mining age with WorldBorder and added a border, so players can mine crystals to their hearts content.

**Comment by seantherobonaut** [comment]
How did you do that by the way? I never found out how to pregen worlds with a certain border.
Also what version of forge do you have and what version of cauldron...if you use it.

**Comment by seantherobonaut** [comment]
It is really kind of funny, there doesn't seem to be anything wrong with the latest mystcraft because he fixed all the older problems. The only real thing we are waiting on is a newer cauldron so we can use a more up to date version of forge so mystcraft works. If only more people worked on cauldron...or sponge came out faster...

**Comment by seantherobonaut** [comment]
Guys....this is the solution to our problems.
https://www.youtube.com/watch?v=G-zthYFjk6s

**Comment by XCompWiz** [comment]
> @ajthemacboy When trying to update my Infinity server to 0.11.3.00, it crashed. Crash report: http://pastebin.com/enqs3fP9
This crash is a result of Cauldron being out of date in respect for Forge, I suspect. At the very least it's not supporting a field which is normally available to Forge mods and must be used in this context.

Binary search tests have been really effective in the past. Sorry don't have the time to do that.

I don't know if RFTools dims allow mod generation to the same extent that Mystcraft does.  I haven't looked at all, I'm afraid.
I checked, but I don't think the chunk remapping was in until 0.11.1, so that isn't it.  That was slow at first and has been optimized since.

At this point, I'd like to ask if one of you would be willing to test this without Cauldron.  Technically, I don't support Cauldron.

**Comment by ajthemacboy** [comment]
I'm using cauldron 1307, this is the full /version output if it tells you anymore: This server is running Cauldron-MCPC-Plus version git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

I will test without Cauldron later today, I guess. Running without Cauldron in the long run is NOT an option on a server with 8-15 people online. RFTools and Twilight Forest both work fine with Cauldron, so it seems to me there is something interfering in your mod.

Also, would you be able to modify a newer version of Mystcraft to be compatible with my 0.11.1.00 clients? I understand some new blocks were added, would it be difficult to remove them so that the server updates and gets the fixes, but the client doesn't have to? (Or maybe just add the improvement to 0.11.1.0)

**Comment by ajthemacboy** [comment]
Lag on a local Forge 1291 server with Mystcraft 0.11.1 still lags quite a bit, but not as bad.

**Comment by ajthemacboy** [comment]
I ran a profile session with Sampler, a mod by Player, that helps profile Minecraft. This is equivalent to using JVisualVM to profile the server. Here is the output:

https://www.dropbox.com/s/o9v1ox6tkahb4rf/Myst2.nps?dl=0

**Comment by XCompWiz** [comment]
Could you try running with the most recent forge?  1291 is even older than the version if Cauldron. :P
...
WOW there are a lot of threads running in Modded...
...
OK, I tracked it down. It's definitely Mystcraft, but it isn't generation; it's profiling.
I'll have to optimize the actual profiling of chunks, clearly.  Perhaps put it in it's own thread.

Thanks for the profiling!  This is very helpful! :)

**Comment by ajthemacboy** [comment]
1291 is still the recommended version for 1.7. Is there any way you can provide these optimizations for 0.11.1, or an update compatible with 1291?

**Comment by XCompWiz** [comment]
For 0.11.1?  You mean provide a patch for that version?  I don't think so, no.  The performance improvements will be rather complex.
Has an issue been created with the Cauldron dev team to fix the field issue?

Mystcraft recommends at least Forge 1340, as it fixes some dimension issues, but I don't think it requires anything higher than 1291, so that's easy enough.

**Comment by ajthemacboy** [comment]
Cauldron is no longer being updated. Since you can't patch it, I just hope
FTB will release an update with the new version once you finish it, a lot
of times they stop supporting packs.

**Comment by XCompWiz** [comment]
Sorry about the Cauldron issue, but there's not much I can do about it at this point.
I do believe that the most recent build resolves the lag issues, though, so I'm going to close this issue as resolved.
