### ISSUE TITLE
(Urgent) Server crashing, Empty chunk errors

### ISSUE THREAD

**Issue by ajthemacboy** [XCompWiz/Mystcraft-Issues#66]
Here is the server log: https://www.dropbox.com/s/t6xc79ngfzk8ywo/latest.log?dl=0

It says the issue is in DIM_MYST-2147483648, but I don't know which world this is to delete it.

For now I can try to delete all the ages, but if this can be fixed, I'd like to restore them. 

This happened after I updated Infinity to 1.4.1, an update which brings Mystcraft 0.11.3 and Forge 1352. Cauldron is version 1343.

**Comment by XCompWiz** [comment]
Mystcraft 0.11.1 and later doesn't run on Cauldron due to some field being removed by Cauldron.
Revert to 0.11 and you'll be fine. (0.11.1 _might_ work, I don't recall).

**Comment by ajthemacboy** [comment]
Revert to 0.11, the one that has extreme lag issues because you introduced laggy code? No thanks. 

Infinity has updated to 1.4.1 and 0.13 is standard now. You are forcing every major FTB server running packs with mystcraft to stay on older versions. This is an issue. 

Is there seriously nothing you can do to make your mod compatible with Cauldron, the STANDARD for servers?

**Comment by ajthemacboy** [comment]
By unanimous vote, we've decided to remove your laggy, buggy mod and play on Infinity 1.4.1. If you ever care to fix this issue in the future, we'll add it back.

Note that we are definitely not the only server that will be doing this.

**Comment by XCompWiz** [comment]
You can revert further, if you like.  Or remove it.  No difference to me.

Cauldron is not the standard for servers.  Sorry, I built Mystcraft for Forge.
Cauldron is the project at fault, not Mystcraft. Removing fields is a good way to break Forge mods.
Cauldron is dead to the best of my knowledge.

At BEST I could check for the field missing and have a fallback system. It would cost me lots of dev time, possibly not fix the issue (if there turned out to be more, similar issues beyond), and the fallback might not work well, as the field was part of the chunk loading system, which means that the chunks wouldn't appear to exist according to whatever system Cauldron is using.

**Comment by ajthemacboy** [comment]
If you go to any FTB servers website (http://ftbservers.com/, http://minecraft-server-list.com/sort/FTB/, etc), I guarantee you that 95% of them run Cauldron.

**Comment by XCompWiz** [comment]
For analogy, just so I can be clear on this, let's say Mystcraft was a program which ran on windows.

You really, really want to run Mystcraft on Linux, but Mystcraft doesn' have a linux build.  Because of the limit dev time available, Mystcraft can't be ported to Linux readily.

Instead, you choose to use Wine.  It runs fine, until Mystcraft uses a feature Wine doesn't currently support.
Would you really go to the developer of Mystcraft and go "your program doesn't run on Wine!"?  I'd go to Wine and say "your emulations doesn't handle feature!" myself.

Now, of course, the problem is that, in our case, "Wine" (Cauldron) is dead.  You can't have it support said feature, because it doesn't update anymore.

Now, if what you say is true about most servers running Cauldron, then you should really get after the FTB team for not testing updates on Cauldron, since they clearly didn't test this update on Cauldron, because it crashes on startup.

**Comment by heldplayer** [comment]
This is not a Mystcraft issue, it's an issue with Cauldron.

If you'd like to use Mystcraft without the issue the only thing you can do is use an older version.

If a workaround were to be added, it would work just the same as the older version, including the lag.

But I repeat, this is not something xComp has to fix because it works fine with vanilla Forge. Cauldron is unsupported.

**Comment by KlutzLament** [comment]
Cauldron is dead. It has been hit with a DMCA takedown. If you insist on sticking with it, you are not going to be able to continue to get updates. Sponge is coming which should serve as a replacement for Bukkit/Cauldron. For now, your choices are to either stick with Cauldron without mod updates or abandon Cauldron and get updates.

**Comment by ajthemacboy** [comment]
I'm sorry I lost my temper. I can see now that this is nobodies fault except Cauldron's for making illegal code. I guess I just have to wait for Sponge.

**Comment by XCompWiz** [comment]
:)
If Cauldron is at fault for anything it's slightly bad code.  The illegal code was Bukkit, and that was a technicality caused by someone pitching a fit.

Thank you very much for apologizing. :)  I really appreciate it.

**Comment by jogi01** [comment]
We MUST use cauldron there is no real alternative out at the moment and nobody ask for mystcraft on my servers nobody need this mod in multiplayer and now the useless and laggy mod prevent us to use new updates very big BULLSHIT!! Lets call the ftb team to remove it entirely from the Modpacks e.g.Infinity

**Comment by heldplayer** [comment]
I sense saltiness, why MUST you use Cauldron? What prevents you from using vanilla Forge?

Bukkit and Cauldron are dead, trying to get support for them is useless.

**Comment by juniorjunior** [comment]
@jogi01: As held mentioned, saltiness yields bitter fruit.

That being said, it is clear that requests of this nature will fall on deaf ears here. "Just use Forge" only works in closed communities where grief/theft/mistakes don't happen. In the real world we require mechanisms for player claims, item/feature restriction, logging, etc. and with the death of Cauldron 6+ months in the past and zero alternatives on anyone's horizon this means that our only option is to use what we can. If this eliminates one mod out of thousands (this being only the second one I have ever come across) it seems a very small loss.

**Comment by jogi01** [comment]
junior youre right but sometimes cleartext is better than have fifty pages full of text like "cauldron is dead use forge blabla" and then "we need plugins and forge dont have plugins" and then "cauldron is not supported" and so on and so on the people dont understand it....

**Comment by KlutzLament** [comment]
There is a project called Sponge that should serve as a replacement to Bukkit/Cauldron. https://www.spongepowered.org/

**Comment by heldplayer** [comment]
So here's a funny thing, I tried to reproduce the issue but I didn't get it to crash with a missing field.

After writing a simple mod that writes out transformed classes, I found that the field is explicitly defined (it has the SRG name, while other fields have nms names)

You may want to look into getting a newer version of Cauldron.

**Comment by ajthemacboy** [comment]
What version of Cauldron did you use? Did you try creating a Mystcraft age?

**Comment by heldplayer** [comment]
I used Cauldron 1.1370.01.0 and tried it with the FTB Infinity modpack (with latest Mystcraft).

I did not try creating a new age because the server crashes after startup with a different error related to IC² and Mystcraft (how ironic :P)

**Comment by ajthemacboy** [comment]
If it crashes on startup, how can you be sure it's stable at all? Assuming
you could fix the ic2 crash, the crash here might happen as well, just in a
later stage.

**Comment by juniorjunior** [comment]
Cauldron 1.1370.01.0 is built using an old source tree and has reintroduced bugs not present in the _1307 and _1381 builds.

Using Cauldron 1.1381.06.221 I am able to successfully start the server with only Mystcraft installed. However, the EmptyChunk issue happens when I put in nearly any other mods (CoFH mods, AM2, Botania, Mantle/Tinkers' mods, Blood Magic, etc.). By stripping out anything that could remotely be related to dimensions (see previous list) I was able to get the server started with only a few of those errors. I could make a random age as well.

**Comment by heldplayer** [comment]
@ajthemacboy I wrote a mod that writes out all classes after they are transformed, I could then look at them by decompiling them and the field was not missing, so I'm reasonably sure it would work (except for the startup issue)

**Comment by Shybella** [comment]
I'm using cauldron with the 1388 Forge update and have not had these issues. Can you tell me exactly what func's are being replaced( you're calling ) so I can attempt a fix. Thank you.

**Comment by Shybella** [comment]
I'm assuming your registering requests through Forge for a world generator for custom blocks and also calling generation lists so it can request the chunk and populate? Those func's to handle those operators don't exist?

**Comment by ajthemacboy** [comment]
Also, I believe the crash on startup might have been caused by loading an ALREADY made Mystcraft age. If someone can test with Infinity 1.4.1 on Cauldron 1370 with Mystcraft age generation, that'd be amazing. (I can test too, of course, but not for a few days.)

**Comment by Shybella** [comment]
This has nothing to do with Cauldron is Forge changes that caused the problem.

**Comment by XCompWiz** [comment]
It's a missing field error, Shy, not a missing function.

I expect that, in your described case case, the problem would be fixed with a newer version of Forge. Forge does it's best to not remove or break fields and methods, so a missing field error should be swiftly repaired in Forge.
In order to make this claim, Shy, can you demonstrate in what version Forge broke the field and if it has repaired the field since?
Alternatively, could you demonstrate that the field was added by Forge, and in what version, showing that it hadn't been added to certain Cauldron versions yet? (I doubt this is the case, as the field name given in the error would suggest that the field is in vanilla and has been removed somehow.)
Either way would give us enough information to know which versions of Forge can be used safely.

**Comment by Shybella** [comment]
loaded chunk hashmap data is missing, this is happen on standalone forge because of fastcraft modification to that field and cauldron does the same. so, anyone using fastcraft with mystcraft will have the same issue, why not use Forges chunk manager?

**Comment by Shybella** [comment]
so, yes im wrong about forge after taking a deeper look

**Comment by ajthemacboy** [comment]
Confirmed, Fastcraft on vanilla forge causes the crash. Could this be grounds for a fix?

**Comment by Shybella** [comment]
Well, xComp is doing a good thing for performance sake by bypassing Forge but this is one issue why its not recommended. Cauldrons really not at fault either, its Spigot the one modifying the field too. FastCraft needs to add support for Mystcraft since its causing the direct problem, Cauldrons issue can be fixed quickly. Then again, Lex advised against doing what both Mystcraft and FastCraft are doing.

**Comment by XCompWiz** [comment]
The dummy dimension has it's own chunk manager because it's not a real dimension and it doesn't want to save anything (or keep many dimensions).  Shy isn't actually in the ball park with what's going on here.

I'm not bypassing Forge.  I've extended the ChunkProviderServer class to override some of it's functionality, allowing me to constrain the number of dimensions loaded and prevent saving of the generated chunks.
In this case, FastCraft would be at fault...  If it actually replaced that field (hint, it doesn't).  However, I'll need to see a log of some kind to be able to say anything on this.  I'll believe it crashed, but I want to see why, and thus need a (crash) log.

**Comment by ajthemacboy** [comment]
Would you mind explaining what the profiling dimension is actually for? I never really understood.. Something to do with ores I think? But, why is it necessary? Dimensions like twilight forest don't have dimensions like this.

**Comment by stevestech** [comment]
Here are the crash logs from the issue I submitted to TPPI:

Cauldron version: 1.7.10-1.1388.1.0
Crash log:
http://paste.ubuntu.com/10921216/
Sometimes I get this one instead:
http://paste.ubuntu.com/10921279/

**Comment by XCompWiz** [comment]
@ajthemacboy  Do you remember The Direwolf20 pack having instability in every age? It's because the baseline stability values were balanced towards vanilla ore distribution.
The purpose of baseline profiling is simply to get what the profiling data should look like on an "average" dimension in your specific mod setup.  Without it, your ages would probably never be stable with other mods.
Simply put, it's Mystcraft auto-balancing itself.  Kind of like what EE3 has to do.
Comparing Twilight Forest to Mystcraft in this regard is a bit like comparing a program to an operating system.  Mystcraft doesn't add a dimension, it adds rules for making dimensions.

Thank you, steve.  To clarify, I was actually asking for a crash log from the Fastcraft conflict. :)  My answer is the same as TPPI's; I don't support Cauldron.
However, it seems that using a newer version of Cauldron (as held demonstrated above) would fix the issue.

**Comment by stevestech** [comment]
@Shybella Can confirm the crashes pasted above occur for me on Cauldron-Reloaded version "1.1388.1.0-Fix1", however I will move this discussion onto the Cauldron-Reloaded github.

**Comment by XCompWiz** [comment]
Reloaded?  Honestly...
Cauldron is dead, and resurrecting it is actually unlawful... That's why it's dead.
Use what Held or JuniorJunior suggested and see if that works.

**Comment by Shybella** [comment]
Then how is Spigot updating? I don't see justification.

**Comment by XCompWiz** [comment]
I don't know, but this isn't the place to discuss it.

**Comment by Shybella** [comment]
Then, I wouldn't say it's unlawful. Cauldron uses Spigot.

**Comment by XCompWiz** [comment]
Edited your post for language.

Doing a bit more research into some things, I can see the reconstruction attempt it trying to rebuild code while leaving out the DMCA'd code.  That's a good approach. All you had to do was point this out.
Regardless, the original Cauldron is still dead, and supporting Sponge would probably be more productive.
I'm not an authority on this, so I can be wrong.  It's also entirely possible that Spigot has just continued in spite of the DMCA, ignoring lawful implications after the point it was a serious issue.  I can't seem to find anything about this.

---
I'm not bypassing Forge in any way.  I'm implementing an extended version of a vanilla class.  This hasn't broken anything in any other mods that I can tell; it just doesn't work on Cauldron because of a missing field.  That's not my fault and it's hard (read: impossible to reasonably) to fix from my side of things.

No mod should have to add compatibility for my dummy dim's chunk handling (Cauldron isn't a mod, as a note).  If there are any issues with other mods then I'm more than happy to help resolve them.

Shy, you've been off base pretty much the whole time. At first you thought it was a method, not a field.  You have found that there is a crash between Mystcraft and Fastcraft and that's helpful, but I still need the crash log for that to verify what's going on.  Please supply that.  I really would like to get to the bottom of that one.  I've already spoken with Player about it, which is how I know that he doesn't replace/remove the field.

And if you wish to resort to threats of "people won't use your mod as much!" then feel free.  I'm not shaken by threats and that's not a threat to me anyway.  I make Mystcraft for fun, so I don't care if people use it or not.
If everyone insisting on using Cauldron stopped using Mystcraft, I'd probably be pretty happy; there'd be lots fewer support issues. :P

**Comment by ajthemacboy** [comment]
This might have already been said but we still crash with Cauldron 1381, the absolute newest version of Cauldron available.

**Comment by Shybella** [comment]
I did not say anything about breaking other mods. I said you're going to cause compatibility issues with your mod. Thus, mixing Fastcraft and Mystcraft as an example. 

You're right, no mod should have to add compatibility. Yet, this is going to address what? Nothing. The issue will still remain. Several mods have problems working together with how you're calling from NMS and not through Forge. This is what I meant for bypassing. Which yes, you're doing. 

Did I not correct myself by saying I was wrong about Forge? I assumed you were using Forge to pull loaded chunk information and I know some registry changes were made recently. That's not the case, so any mod that attempts to interact with Mystcraft will not work properly or if another mod modifies NMS like Fastcraft which only mods such as Fastcraft should only do since this is intended for its use. 

Yes, those threads have been popping up and you'll see more issues about Cauldron and other mod compatibility come up more. It's your choice on what you do and I totally respect your dissension.

**Comment by XCompWiz** [comment]
@Shybella You just don't sound very respectful.  Perhaps it's the text medium.

You did correct yourself. Thank you.

No functions were harmed in the making of this issue. :P
Field is a variable, not a function. The field (variable) has been removed by something.  There was no function removed and I'm not making a function call that's failing.

NMS? Would you care to elaborate?  No mods should have issues with me replacing the ServerChunkProvider for my dimension.
I'm not calling anything; I'm replacing a variable instance. Should be invisible to anything using the class, which I think only vanilla will.
Can you give a concrete example of issues caused, please?  Preferably as a new issue with a log or examples of broken behavior (w/ screenshots).

It's not my call whether anyone wants to update Cauldron. Never said it was. I just said it's dead, and that it's probably better to move to working on Sponge. Sponge is planned to be backported to 1.7 once stable.  We'll have Sponge sooner with more people working on it, so all the effort in Cauldron clones would probably yield more use invested into Sponge.

If there are issues I can fix, I generally will.  With an issue like this, I'd normally take it to the other mod author.  Since that's not possible here, I hope something else can be worked out.
Any issues with other mods that crop up I'll be active in resolving.  Again, Cauldron is not a mod (it's a platform, like Forge), and I have NEVER supported it.  Despite this, I've still gone out of my way to help where I could.

@ajthemacboy That's unfortunate.  Do you mean the 1.1381.06.221 version?  Can you verify that it is the exact same crash, or is it perhaps something slightly different?

---
Would someone who has encountered the crash with Fastcraft *please* link a pastebin log?

**Comment by Shybella** [comment]
I'm done with this issue. Here's a list of mods that will have conflicts with using your method.

- Natura
- Thaumcraft
- TwilightForest
- Fastcraft

Potential mod conflict . 

- Harvestcraft
- Denseores
- TConstruct
- Chisel
- Forestry

Mods that have this worked around already.

- Applied Energistics 2
- Draconic Evolution
- Witchery
- Extra Utilities
- ExtraBees

Another mod that used this same type of method as Mystcraft and fixed it.

- IC2

You're not even registering the DIM correctly with Forge. So, any mod that hooks onto generation using Forge. 

Also, after investigating. I was wrong about Spigot with Cauldron. You're crash with Cauldron is from Thaumcraft trying to generate in a Mystcraft DIM.

Here's your fix. Edit this inside your Cauldron config. Change the value from true to false as below. 
worldgen-Mystcraft-MystWorldGenerator: false

**Comment by XCompWiz** [comment]
You keep making claims without any backup. I can't act without more information.
You want to tell me what those conflicts will be? What will break?

What have the listed mods worked around?  How?

I'm fairly certain that I DO register my dummy dimension... *goes to check* Yup. Sure do.
I'm not sure how it could be incorrectly at all.  Are you worried because of the dynamic nature of it?  All of my dimension registration is dynamic, and happens after the server has started, Nothing new there.

Who's crash with Cauldron is caused by Thaumcraft?  Because the crash with Cauldron in the logs is a missing field error encountered in my code because a field is missing from a vanilla class.

**Comment by heldplayer** [comment]
@Shybella I'm going to kindly request you to post logs of the crashes that are caused by your claimed incompatibilities and what caused them to happen. If you can't manage that you're better off barking at a tree.

No mod should EVER remove a field from vanilla classes (and none are doing so as far as I know), except Cauldron is not a mod. And cauldron is also dead officially, which means the support for it has ended (unofficial builds are even more unsupported).

**Comment by ajthemacboy** [comment]
@XCompWiz Yes, I meant the 1.1381.06.221 version. Here is the error: http://paste.ubuntu.com/10955203/

**Comment by XCompWiz** [comment]
No, that's a different error.  That might mean some progress. :)

Is that actually causing you to crash?  The issue at this point appears to be that empty chunks are being generated.  This is intentional, to avoid generating out of bounds chunks (the world can only store so many chunks, and it's not useful to go generate chunks we don't want).
Vanilla doesn't have issues with this, but other mods (and Cauldron) *might*.  Thus far I haven't seen any issues arise (most things should handle the innate EmptyChunk fairly well), and the innate EmptyChunk looks like a normal chunk... just empty... :P
Though here it kind of looks like Cauldron has decided to arbitrarily pitch a fit over the empty chunk.  I *might* be able to bypass that if I can figure out where it's being done.

**Comment by XCompWiz** [comment]
@ajthemacboy Would you be so kind as to create a new issue for this error?  This issue has become rather cluttered. :)
And it seems I would be able to replace the function that is throwing these errors, if that is desired.  In this case, I would just make the function identical to what it does in vanilla. However, I'm uncertain what that would do to Cauldron otherwise.

**Comment by ajthemacboy** [comment]
Whoops, didn't notice there was a crash report.. the errors above are spammed in chat before the server crashes with this error: http://paste.ubuntu.com/10955457/

**Comment by XCompWiz** [comment]
OK, good that those aren't crashing the server. They are just annoying.  We can live with them.

This is altogether different...  And entirely inside craftbukkit.
Something about bukkit's custom getBlock implementation there is breaking, but I can't begin to guess what.  This would need to be addressed or looked at from that side...
Can someone get the code for that function for me?

And, same request, aj. Can you open a new issue? We've covered the old one to death, and we've moved past it. This is a different issue.

**Comment by ajthemacboy** [comment]
Sorry, I haven't been following the thread closely. I was just providing the logs for you :)
Let me know if you need more information.

**Comment by devryb** [comment]
Same issue here with the dummy dimension, we just removed Mystcraft all together.  Funny thing is the players didn't even really care/notice :)
