### ISSUE TITLE
Build 0.11.6.00 beta Crash on start up

### ISSUE THREAD

**Issue by aldra2012** [XCompWiz/Mystcraft-Issues#71]
http://pastebin.com/rQ7Swt5e

**Comment by bigbantha** [comment]
same here

**Comment by XCompWiz** [comment]
Hmmm....  Looks like something was, in fact, using my old API. I didn't think anything was.
I can change the IMC message to request the API provider, and that should fix this, but I don't understand why it crashed.  I have guards to catch this specific error (and, in fact, all Exceptions at this point), and yet it went right past those checks.
Looks like, if the crash happens in class loading, it doesn't care where we were in execution. Annoying.  I'd thought that we'd get a nice little "This mod is using the old API!" message.

In this context, an actual log would be REALLY helpful.  If you could provide that, rather than the crash log I'd appreciate it.  Note that actual logs are always better than crash logs.

**Comment by TheJulianJES** [comment]
Is it maybe OpenPeripheral or something like that?
