### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Usverin** [XCompWiz/Mystcraft-Issues#78]
A lot of 
[11:36:14] [Server thread/INFO] [STDERR/]: [net.minecraftforge.common.DimensionManager:initDimension:238]: Cannot Hotload Dim: Could not get provider type for dimension -2147483648, does not exist

while starting server.

Mystcraft 0.11.7.00

fml-server-latest.log - https://drive.google.com/file/d/0B3d5EdoI8zcjeTN6aWJyTG13Ykk/view?usp=sharing

**Comment by Usverin** [comment]
cause is ChickenChunks

tried with the same result
last
ChickenChunks	1.3.4.19
CodeChickenCore	1.0.6.43

and
recommended
ChickenChunks	1.3.4.16
CodeChickenCore	1.0.4.29

what i have to do to fix it?

**Comment by XCompWiz** [comment]
Earlier in the log there is:
```
[11:34:37] [Server thread/INFO] [enviromine/]: New mine at 1792,80,0 with rotation 0 in dimension -2147483648
```
This means that the dimension has loaded without problem and started generating, but sometime after that we get the error you referenced. This means that either the dimension provider was never at that id (it got another id) or something removed it.

I think that something is forcing my world to unload prematurely, probably ChickenChunks.  Clearly it has some logic built into it to force the world to unload, and when that happens y system cleans up, thinking that it's done or the game is being shutdown.

Since there is still generation going on, things then crash.  I'd expect that whatever logic ChickenBones has put in would conflict with anything doing dimension preloading, so I'd suggest you take this to him and get him to fix it.  If a dimension is constantly getting new chunks, it really doesn't need to be force unloaded...
Really, ChickenChunks shouldn't be force unloading dimensions in my book, anyway, but...

**Comment by XCompWiz** [comment]
To clarify, I AM trying to handle this case, as I prefer my code to be robust.  However, CB still should fix that logic.  It can easily end up in a cycle of the world loading and unloading really quickly, which will be murder on a server.

**Comment by Usverin** [comment]
ok....perhaps it could be helpful 
ChickenChunks + appliedenergistics2-rv2-beta-31.jar/appliedenergistics2-rv2-beta-32.jar=my case

**Comment by XCompWiz** [comment]
More on this: If the world is forcibly unloaded frequently enough, my profiling may never be able to actually get going, as the chunk generation is discarded, not saved.  Either way, the world being unloaded WILL result in wasted effort and the profiling taking much longer.

I am turning on the flag for "keep loaded" for the provider, but I worry about other mods picking up on that and doing things with chunk loading...

**Comment by Usverin** [comment]
0o 
Fixed by reseting configs of Enviromine
Thnx for your help and sorry for the disturbance :(

**Comment by XCompWiz** [comment]
Weird. OK. :+1: Sorry, CB; I was modeling based off of information that removing ChickenChunks fixed it.
