### ISSUE TITLE
Dependency error on startup

### ISSUE THREAD

**Issue by EXTER7** [XCompWiz/Mystcraft-Issues#91]
After updating Mystcraft and LookingGlass, the game stops at the startup and displays the following error:
![screenshot](https://cloud.githubusercontent.com/assets/3077881/7904053/3e8b4280-07bc-11e5-8b9d-14a0fba64436.png)

[Error section from the log file](http://pastebin.com/VvgnP6RR)

Versions:
Mystcraft 0.11.11.00
LookingGlass 0.1.0.00

**Comment by XCompWiz** [comment]
"The mod NEI-Mystcraft-Plugin (NEI Mystcraft Plugin) requires mod versions"
Remove the Mystcraft NEI mod or revert it to a pre-LookingGlass version. :)
@heldplayer will have to update the plugin.
Held, for starters, your version requirement is "version equal to or prior" here.  Second, do NOT have a hard requirement on LookingGlass in the NEI plugin.

**Comment by heldplayer** [comment]
It is indeed my mod.

I've added a requirement to prevent crashing that if LookingGlass is installed, it needs to be at most 0.0.1.01

It's in there right now because I couldn't get a clean way to make both the alpha and the release version of LG to work with my addon.

Next release will be for the new LG version :)
